# Generated by Django 4.2.9 on 2024-01-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_hashtag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='제목'),
        ),
    ]
